### ISSUE TITLE
Example of output from gatherup (not a real issue!)

### ISSUE THREAD

**Issue by nmstoker** [nmstoker/gatherup#2]
This is not a real issue, it's simply an example of the output when run on the conda environment I have been using to develop gatherup. The purpose is simply to give a quick idea of what the formatted output looks like.

### Platform OS

* **Linux**

### Python Environment

* **Python 3.7.6**

* Virtual env: **Conda**

### Package Installation

* Project installed via Pip
<br>
<details>
  <summary>Click to see package list (package count: 78)</summary><br>

  :package: Package list from Conda
  
  | Package  | Version |
  | ------------- | ------------- |
  |_libgcc_mutex|0.1|
  |_openmp_mutex|4.5|
  |attrs|19.3.0|
  |backcall|0.2.0|
  |bleach|3.1.5|
  |ca-certificates|2020.6.20|
  |certifi|2020.6.20|
  |cffi|1.14.1|
  |chardet|3.0.4|
  |check-manifest|0.42|
  |click|7.1.2|
  |colorama|0.4.3|
  |commonmark|0.9.1|
  |confuse|1.3.0|
  |cryptography|3.0|
  |decorator|4.4.2|
  |docutils|0.16|
  |gatherup|0.0.1|
  |idna|2.10|
  |importlib-metadata|1.7.0|
  |iniconfig|1.0.0|
  |ipython|7.16.1|
  |ipython_genutils|0.2.0|
  |jedi|0.17.2|
  |jeepney|0.4.3|
  |keyring|21.3.0|
  |ld_impl_linux-64|2.34|
  |libffi|3.2.1|
  |libgcc-ng|9.2.0|
  |libgomp|9.2.0|
  |libstdcxx-ng|9.2.0|
  |more-itertools|8.4.0|
  |ncurses|6.1|
  |openssl|1.1.1g|
  |packaging|20.4|
  |parso|0.7.0|
  |pep517|0.8.2|
  |pexpect|4.8.0|
  |pickleshare|0.7.5|
  |pip|20.1.1|
  |pkginfo|1.5.0.1|
  |pluggy|0.13.1|
  |pprintpp|0.4.0|
  |prompt-toolkit|3.0.5|
  |ptyprocess|0.6.0|
  |py|1.9.0|
  |pycparser|2.20|
  |pygments|2.6.1|
  |pyparsing|2.4.7|
  |pyperclip|1.8.0|
  |pytest|6.0.0|
  |python|3.7.6|
  |python_abi|3.7|
  |pyyaml|5.3.1|
  |questionary|1.5.2|
  |readline|8.0|
  |readme-renderer|26.0|
  |requests|2.24.0|
  |requests-toolbelt|0.9.1|
  |rfc3986|1.4.0|
  |rich|3.3.2|
  |secretstorage|3.1.2|
  |setuptools|49.2.0|
  |six|1.15.0|
  |sqlite|3.32.3|
  |tk|8.6.10|
  |toml|0.10.1|
  |tqdm|4.48.2|
  |traitlets|4.3.3|
  |twine|3.2.0|
  |typing-extensions|3.7.4.2|
  |urllib3|1.25.10|
  |wcwidth|0.2.5|
  |webencodings|0.5.1|
  |wheel|0.34.2|
  |xz|5.2.5|
  |zipp|3.1.0|
  |zlib|1.2.11|
  

</details>

## Configuration

<details>
  <summary>Click to see config file (lines: 146)</summary><br>

  :page_facing_up: Contents from: **/home/neil/.config/gatherup/example_files/example_config_1.json**
  
  ````javascript
  {
      "model": "Tacotron2",
      "run_name": "ljspeech",
      "run_description": "tacotron2",
  
      // AUDIO PARAMETERS
      "audio":{
          // stft parameters
          "num_freq": 513,         // number of stft frequency levels. Size of the linear spectogram frame.
          "win_length": 1024,      // stft window length in ms.
          "hop_length": 256,       // stft window hop-lengh in ms.
          "frame_length_ms": null, // stft window length in ms.If null, 'win_length' is used.
          "frame_shift_ms": null,  // stft window hop-lengh in ms. If null, 'hop_length' is used.
  
          // Audio processing parameters
          "sample_rate": 22050,   // DATASET-RELATED: wav sample-rate. If different than the original data, it is resampled.
          "preemphasis": 0.0,     // pre-emphasis to reduce spec noise and make it more structured. If 0.0, no -pre-emphasis.
          "ref_level_db": 20,     // reference level db, theoretically 20db is the sound of air.
  
          // Silence trimming
          "do_trim_silence": true,// enable trimming of slience of audio as you load it. LJspeech (false), TWEB (false), Nancy (true)
          "trim_db": 60,          // threshold for timming silence. Set this according to your dataset.
  
          // Griffin-Lim
          "power": 1.5,           // value to sharpen wav signals after GL algorithm.
          "griffin_lim_iters": 60,// #griffin-lim iterations. 30-60 is a good range. Larger the value, slower the generation.
  
          // MelSpectrogram parameters
          "num_mels": 80,         // size of the mel spec frame.
          "mel_fmin": 0.0,        // minimum freq level for mel-spec. ~50 for male and ~95 for female voices. Tune for dataset!!
          "mel_fmax": 8000.0,     // maximum freq level for mel-spec. Tune for dataset!!
  
          // Normalization parameters
          "signal_norm": true,    // normalize spec values. Mean-Var normalization if 'stats_path' is defined otherwise range normalization defined by the other params.
          "min_level_db": -100,   // lower bound for normalization
          "symmetric_norm": true, // move normalization to range [-1, 1]
          "max_norm": 4.0,        // scale normalization to range [-max_norm, max_norm] or [0, max_norm]
          "clip_norm": true,      // clip normalized values into the range.
          "stats_path": null    // DO NOT USE WITH MULTI_SPEAKER MODEL. scaler stats file computed by 'compute_statistics.py'. If it is defined, mean-std based notmalization is used and other normalization params are ignored
      },
  
      // VOCABULARY PARAMETERS
      // if custom character set is not defined,
      // default set in symbols.py is used
      // "characters":{
      //     "pad": "_",
      //     "eos": "~",
      //     "bos": "^",
      //     "characters": "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz!'(),-.:;? ",
      //     "punctuations":"!'(),-.:;? ",
      //     "phonemes":"iyɨʉɯuɪʏʊeøɘəɵɤoɛœɜɞʌɔæɐaɶɑɒᵻʘɓǀɗǃʄǂɠǁʛpbtdʈɖcɟkɡqɢʔɴŋɲɳnɱmʙrʀⱱɾɽɸβfvθðszʃʒʂʐçʝxɣχʁħʕhɦɬɮʋɹɻjɰlɭʎʟˈˌːˑʍwɥʜʢʡɕʑɺɧɚ˞ɫ"
      // },
  
      // DISTRIBUTED TRAINING
      "distributed":{
          "backend": "nccl",
          "url": "tcp:\/\/localhost:54321"
      },
  
      "reinit_layers": [],    // give a list of layer names to restore from the given checkpoint. If not defined, it reloads all heuristically matching layers.
  
      // TRAINING
      "batch_size": 32,       // Batch size for training. Lower values than 32 might cause hard to learn attention. It is overwritten by 'gradual_training'.
      "eval_batch_size":16,
      "r": 7,                 // Number of decoder frames to predict per iteration. Set the initial values if gradual training is enabled.
      "gradual_training": [[0, 7, 64], [1, 5, 64], [50000, 3, 32], [130000, 2, 32], [290000, 1, 32]], //set gradual training steps [first_step, r, batch_size]. If it is null, gradual training is disabled. For Tacotron, you might need to reduce the 'batch_size' as you proceeed.
      "loss_masking": true,         // enable / disable loss masking against the sequence padding.
      "ga_alpha": 10.0,        // weight for guided attention loss. If > 0, guided attention is enabled.
  
      // VALIDATION
      "run_eval": true,
      "test_delay_epochs": 10,  //Until attention is aligned, testing only wastes computation time.
      "test_sentences_file": null,  // set a file to load sentences to be used for testing. If it is null then we use default english sentences.
  
      // OPTIMIZER
      "noam_schedule": false,        // use noam warmup and lr schedule.
      "grad_clip": 1.0,              // upper limit for gradients for clipping.
      "epochs": 1000,                // total number of epochs to train.
      "lr": 0.0001,                  // Initial learning rate. If Noam decay is active, maximum learning rate.
      "wd": 0.000001,                // Weight decay weight.
      "warmup_steps": 4000,          // Noam decay steps to increase the learning rate from 0 to "lr"
      "seq_len_norm": false,         // Normalize eash sample loss with its length to alleviate imbalanced datasets. Use it if your dataset is small or has skewed distribution of sequence lengths.
  
      // TACOTRON PRENET
      "memory_size": -1,             // ONLY TACOTRON - size of the memory queue used fro storing last decoder predictions for auto-regression. If < 0, memory queue is disabled and decoder only uses the last prediction frame.
      "prenet_type": "original",     // "original" or "bn".
      "prenet_dropout": true,        // enable/disable dropout at prenet.
  
      // ATTENTION
      "attention_type": "original",  // 'original' or 'graves'
      "attention_heads": 4,          // number of attention heads (only for 'graves')
      "attention_norm": "sigmoid",   // softmax or sigmoid. Suggested to use softmax for Tacotron2 and sigmoid for Tacotron.
      "windowing": false,            // Enables attention windowing. Used only in eval mode.
      "use_forward_attn": false,     // if it uses forward attention. In general, it aligns faster.
      "forward_attn_mask": false,    // Additional masking forcing monotonicity only in eval mode.
      "transition_agent": false,     // enable/disable transition agent of forward attention.
      "location_attn": true,         // enable_disable location sensitive attention. It is enabled for TACOTRON by default.
      "bidirectional_decoder": false,  // use https://arxiv.org/abs/1907.09006. Use it, if attention does not work well with your dataset.
  
      // STOPNET
      "stopnet": true,               // Train stopnet predicting the end of synthesis.
      "separate_stopnet": true,      // Train stopnet seperately if 'stopnet==true'. It prevents stopnet loss to influence the rest of the model. It causes a better model, but it trains SLOWER.
  
      // TENSORBOARD and LOGGING
      "print_step": 25,       // Number of steps to log traning on console.
      "print_eval": false,     // If True, it prints intermediate loss values in evalulation.
      "save_step": 10000,      // Number of training steps expected to save traninpg stats and checkpoints.
      "checkpoint": true,     // If true, it saves checkpoints per "save_step"
      "tb_model_param_stats": false,     // true, plots param stats per layer on tensorboard. Might be memory consuming, but good for debugging.
  
      // DATA LOADING
      "text_cleaner": "phoneme_cleaners",
      "enable_eos_bos_chars": false, // enable/disable beginning of sentence and end of sentence chars.
      "num_loader_workers": 4,        // number of training data loader processes. Don't set it too big. 4-8 are good values.
      "num_val_loader_workers": 4,    // number of evaluation data loader processes.
      "batch_group_size": 0,  //Number of batches to shuffle after bucketing.
      "min_seq_len": 6,       // DATASET-RELATED: minimum text length to use in training
      "max_seq_len": 153,     // DATASET-RELATED: maximum text length
  
      // PATHS
      "output_path": "/home/xxx/xxx/",
  
      // PHONEMES
      "phoneme_cache_path": "/home/xxx/xxx/phonemes",  // phoneme computation is slow, therefore, it caches results in the given folder.
      "use_phonemes": false,           // use phonemes instead of raw characters. It is suggested for better pronounciation.
      "phoneme_language": "en-us",     // depending on your target language, pick one from  https://github.com/bootphon/phonemizer#languages
  
      // MULTI-SPEAKER and GST
      "use_speaker_embedding": false,     // use speaker embedding to enable multi-speaker learning.
      "style_wav_for_test": null,          // path to style wav file to be used in TacotronGST inference.
      "use_gst": false,       // TACOTRON ONLY: use global style tokens
  
      // DATASETS
      "datasets":   // List of datasets. They all merged and they get different speaker_ids.
          [
              {
                  "name": "ljspeech",
                  "path": "/home/xxx/xxx/",
                  "meta_file_train": "metadata.csv",
                  "meta_file_val": null
              }
          ]
  
  }
  
  
  ````
  

</details>

## Traceback

<details>
  <summary>Click to see traceback extract (lines: 6)</summary><br>

  :page_facing_up: Traceback extract from: **/home/neil/.config/gatherup/example_files/log_with_traceback.log**
  
  ~~~
  Traceback (most recent call last):
    File "/path/to/example.py", line 4, in <module>
      greet('Chad')
    File "/path/to/example.py", line 2, in greet
      print('Hello, ' + someon)
  NameError: name 'someon' is not defined
  
  ~~~
  

</details>

## Logfile

<details>
  <summary>Click to see log file (lines: 16)</summary><br>

  :page_facing_up: Logfile: **/home/neil/.config/gatherup/example_files/log_with_traceback.log**
  
      This is just dummy content for a log file!
      [2020-07-13] Blah blah blah
      [2020-07-13] Blah blah blah
      [2020-07-13] Blah blah blah
      [2020-07-14] Blah blah blah
      [2020-07-14] Blah blah blah
      [2020-07-14] Blah blah blah
      [2020-07-14] Blah blah blah
      Now something bad is tried. Next line is a traceback (not this line :-) )
      Traceback (most recent call last):
        File "/path/to/example.py", line 4, in <module>
          greet('Chad')
        File "/path/to/example.py", line 2, in greet
          print('Hello, ' + someon)
      NameError: name 'someon' is not defined
  
  

</details>

_- generated at 01:34 on Aug 06 2020 using [Gather Up](https://github.com/nmstoker/gatherup) tool_ :gift:

**Comment by nmstoker** [comment]
As this was merely a demo of the normal output from gatherup and not a real issue, I will close it.

_Please_ resist the temptation to submit gatherup output here (unless it's genuinely relating to an issue!) :slightly_smiling_face:
